<a href="https://colab.research.google.com/github/RobertBWeidlich/Colab_Notebooks/blob/main/CnNb_020_02_PiAware.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Read a Piaware JSON data file, convert to a Python object,
# and do some simple analysis with Pandas.

In [ ]:
# Download data
!mkdir /content/data/
!cd /content/data/
#!sftp user@X.X.X.X # this doesn't work...
!ls -l
!mget piaware-data-2024-10.tar

In [ ]:
PIAWARE_DATA_DIR="/content/data/2024/"

import os

def list_files_recursively(directory):

    # Walk through the directory
    file_list = []
    for dirpath, dirnames, filenames in os.walk(directory):
        for filename in filenames:
            # Join the directory path with the file name to get the full path
            filepath = os.path.join(dirpath, filename)
            #print(filepath)
            file_list.append(filepath)
    return file_list

file_list = list_files_recursively(PIAWARE_DATA_DIR)
file_list_len = len(file_list)
print(f"{file_list_len} files in file_list")

32957 files in file_list

In [ ]:
# pick a random file
file_list_len = len(file_list)
file_index = int(file_list_len * 0.35)
print(file_list_len)
print(file_index)

pa_file = file_list[file_index]
print(f"pa_file: {pa_file}")
try:
  with open(pa_file, 'r') as file:
    # Read the contents of the file
    contents = file.read()
    # Print the file contents
    print(contents)
except FileNotFoundError:
  print(f"The file '{file_name}' was not found.")
except IOError:
  print(f"An error occurred while trying to read the file '{file_name}'.")

In [ ]:
import json
from pprint import pprint

# Open the JSON file and load its data into a Python object
#with open('filename.json', 'r') as file:
with open(pa_file, 'r') as fp:
    data = json.load(fp) # data is type dict
    print(f"type(data): {type(data)}")

# Pretty print the data
pprint(data)

In [ ]:
import json
import pandas as pd

# Open the JSON file and load it
#with open('filename.json', 'r') as file:
with open(pa_file, 'r') as file:
    data = json.load(file)

# Convert the loaded JSON data to a pandas DataFrame
df = pd.DataFrame(data)

# Print the DataFrame
# Set Pandas options to display all rows and columns
pd.set_option('display.max_rows', None)      # Display all rows
pd.set_option('display.max_columns', None)   # Display all columns
#print(df)
#df.to_string()
df.head(1000)

In [ ]:
# prompt: flatten this data frame

import pandas as pd

# Assuming 'df' is your DataFrame from the previous code

df_flattened = pd.json_normalize(data['aircraft']).sort_values(by='hex', ascending=True)


# print(df_flattened)
df_flattened.head(40)

,hex,alt_baro,version,nac_p,sil,sil_type,mlat,tisb,messages,seen,rssi,alt_geom,gs,track,baro_rate,nav_qnh,nav_altitude_mcp,nav_heading,lat,lon,nic,rc,seen_pos,nic_baro,nac_v,gva,sda,flight,squawk,emergency,category,geom_rate,nav_altitude_fms,nav_modes
13,a01f73,8750.0,2.0,10.0,3.0,perhour,[],[],1252,6.6,-14.2,9250.0,296.5,26.7,-64.0,1022.4,9024.0,NaN,38.723373,-77.042820,8.0,186.0,8.7,1.0,2.0,2.0,2.0,RPA4421,4607,none,A3,NaN,NaN,"[autopilot, althold, tcas]"
17,a03510,3100.0,2.0,10.0,3.0,perhour,[],[],1412,0.1,-4.1,3350.0,274.1,1.5,NaN,1022.4,3008.0,12.0,38.947906,-77.350796,8.0,186.0,0.4,1.0,1.0,2.0,2.0,EJA112,0570,none,A3,-896.0,NaN,NaN
85,a03f1e,NaN,2.0,NaN,NaN,perhour,[],[],12370,114.3,-17.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A3,NaN,NaN,NaN
9,a05470,34000.0,2.0,10.0,3.0,perhour,[],[],331,0.0,-11.7,35350.0,395.2,236.4,64.0,1013.6,34016.0,NaN,39.798020,-76.395691,8.0,186.0,0.9,1.0,2.0,2.0,2.0,RPA4418,NaN,NaN,A3,NaN,NaN,"[autopilot, vnav, tcas]"
23,a05bde,13100.0,2.0,10.0,3.0,perhour,[],[],582,3.4,-13.5,13775.0,352.4,59.3,1856.0,1022.4,19008.0,NaN,39.048250,-76.762146,8.0,186.0,5.1,1.0,2.0,2.0,2.0,RPA4373,5627,none,A3,NaN,NaN,"[autopilot, vnav, tcas]"
49,a071c8,38000.0,2.0,10.0,3.0,perhour,[],[],5175,0.2,-10.6,39675.0,376.9,225.1,NaN,1012.8,38016.0,242.6,39.034836,-76.943406,8.0,186.0,0.6,1.0,1.0,2.0,2.0,DAL2412,3350,none,A3,0.0,NaN,NaN
84,a08f62,NaN,2.0,NaN,NaN,perhour,[],[],7563,173.8,-18.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A2,NaN,NaN,NaN
16,a0d72b,35025.0,2.0,9.0,3.0,perhour,[],[],1340,0.8,-17.4,36700.0,503.2,32.6,0.0,1013.6,35008.0,NaN,38.313190,-76.506401,8.0,186.0,12.6,1.0,1.0,2.0,2.0,AAL1379,6051,none,A3,NaN,NaN,NaN
67,a114f4,NaN,2.0,NaN,NaN,perhour,[],[],183,0.5,-16.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AAL9834,NaN,NaN,A3,NaN,NaN,NaN
36,a1623f,30000.0,2.0,10.0,3.0,perhour,[],[],2049,1.4,-14.5,31325.0,263.0,242.9,0.0,1013.6,30016.0,254.5,39.310246,-78.038269,9.0,75.0,1.8,1.0,2.0,2.0,2.0,N189BL,2762,none,A1,NaN,NaN,"[autopilot, althold, lnav]"
86,a1696b,36000.0,2.0,NaN,NaN,perhour,[],[],11019,17.6,-18.2,37725.0,381.0,238.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,A3,NaN,NaN,NaN
59,a19f29,NaN,2.0,NaN,NaN,perhour,[],[],667,138.0,-17.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A3,NaN,NaN,NaN
44,a1bd4d,4750.0,2.0,10.0,3.0,perhour,[],[],973,17.6,-16.6,4950.0,101.1,205.8,-128.0,1021.6,4992.0,208.1,38.965527,-77.731689,9.0,75.0,19.0,1.0,2.0,2.0,2.0,AVL211,4642,none,A1,NaN,NaN,NaN
78,a1d93b,NaN,2.0,NaN,NaN,perhour,[],[],4799,99.0,-17.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A3,NaN,NaN,NaN
38,a1ea70,19675.0,2.0,NaN,NaN,perhour,[],[],1623,4.3,-16.2,20600.0,407.0,243.1,2240.0,NaN,NaN,NaN,38.486318,-77.808960,8.0,186.0,4.6,NaN,2.0,NaN,NaN,NaN,NaN,NaN,A3,NaN,NaN,NaN
52,a2147c,NaN,2.0,NaN,NaN,perhour,[],[],1405,62.8,-17.5,NaN,507.4,42.7,-64.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,A3,NaN,NaN,NaN
43,a2da7f,3775.0,2.0,10.0,3.0,perhour,[],[],3646,0.3,-12.8,4025.0,234.3,51.8,NaN,1022.4,4000.0,90.0,39.141495,-77.559715,8.0,186.0,5.6,1.0,1.0,2.0,2.0,PWR3,7324,none,A2,-128.0,NaN,NaN
58,a2e045,NaN,2.0,NaN,NaN,perhour,[],[],2760,69.5,-15.9,NaN,506.7,42.6,-2560.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,A3,NaN,NaN,NaN
54,a2e516,25225.0,2.0,10.0,3.0,perhour,[],[],5443,0.2,-12.4,26475.0,497.9,45.8,NaN,1013.6,24000.0,56.2,39.273972,-76.293600,8.0,186.0,1.1,1.0,1.0,2.0,2.0,N286JJ,3443,none,A2,-2560.0,NaN,NaN
18,a3298a,35000.0,2.0,10.0,3.0,perhour,[],[],194,0.1,-13.7,36675.0,489.9,32.7,NaN,1012.8,35008.0,36.6,38.002396,-76.766091,8.0,186.0,0.2,1.0,1.0,2.0,2.0,JBU1310,0745,NaN,A3,-64.0,NaN,NaN
71,a36f1d,NaN,2.0,NaN,NaN,perhour,[],[],2252,263.5,-15.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A2,NaN,NaN,NaN
47,a38cd2,5750.0,2.0,10.0,3.0,perhour,[],[],1558,3.2,-16.3,6100.0,232.6,183.9,0.0,1022.4,6016.0,NaN,39.005701,-76.851562,8.0,186.0,3.7,1.0,2.0,2.0,2.0,NaN,NaN,NaN,A3,NaN,NaN,"[autopilot, althold, tcas]"
79,a3c3e0,34000.0,2.0,NaN,NaN,perhour,[],[],10168,2.3,-17.5,35575.0,407.2,233.2,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,A4,NaN,NaN,NaN
50,a40312,34025.0,2.0,10.0,3.0,perhour,[],[],5146,0.0,-4.9,35600.0,407.3,225.0,0.0,1012.8,34016.0,NaN,38.857498,-77.171611,8.0,186.0,0.2,1.0,4.0,2.0,3.0,FFT3355,2673,none,A3,NaN,NaN,NaN
64,a4105b,NaN,2.0,NaN,NaN,perhour,[],[],2105,210.3,-17.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A3,NaN,NaN,NaN
73,a44166,NaN,2.0,NaN,NaN,perhour,[],[],3826,124.3,-18.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A3,NaN,NaN,NaN
57,a44b56,34000.0,2.0,9.0,3.0,perhour,[],[],7547,0.1,-2.1,35625.0,408.7,225.0,0.0,1013.6,34016.0,0.0,38.750381,-77.308462,8.0,186.0,0.1,1.0,1.0,2.0,2.0,DAL1514,1767,none,A3,NaN,NaN,NaN
2,a44e1c,34000.0,2.0,10.0,3.0,perhour,[],[],296,16.8,-16.4,35450.0,401.0,236.4,0.0,1013.6,34016.0,248.9,39.903854,-76.189171,8.0,186.0,22.4,1.0,2.0,2.0,2.0,DAL2411,3054,none,A3,NaN,NaN,NaN
29,a45e8a,NaN,0.0,NaN,NaN,unknown,[],[],37,256.0,-17.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,a4910c,NaN,2.0,10.0,3.0,perhour,[],[],516,39.5,-18.0,NaN,NaN,NaN,NaN,1024.0,17504.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,A1,NaN,NaN,[althold]
20,a4bfc7,42975.0,2.0,10.0,3.0,perhour,[],[],581,8.9,-13.6,44600.0,382.9,220.8,NaN,1012.8,43008.0,240.5,39.356049,-76.698602,8.0,186.0,9.8,1.0,1.0,2.0,2.0,LXJ405,1136,none,A2,0.0,NaN,NaN
5,a4ee36,18500.0,0.0,8.0,2.0,unknown,[],[],36,6.3,-16.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2641,none,NaN,NaN,NaN,NaN
61,a4ef54,NaN,2.0,NaN,NaN,perhour,[],[],1734,29.4,-16.1,NaN,175.0,233.1,1152.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,A1,NaN,NaN,NaN
48,a4f1e5,32000.0,2.0,9.0,3.0,perhour,[],[],1440,2.4,-9.3,33425.0,410.2,238.6,0.0,1012.8,32000.0,NaN,39.440173,-77.733337,8.0,186.0,2.8,1.0,1.0,2.0,3.0,AAL655,1147,none,A3,NaN,NaN,NaN
83,a52844,NaN,2.0,NaN,NaN,perhour,[],[],10255,35.4,-14.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A2,NaN,NaN,NaN
65,a536dd,43000.0,2.0,10.0,3.0,perhour,[],[],3335,0.6,-14.9,44575.0,349.1,250.9,0.0,1013.6,43008.0,NaN,39.586533,-77.512247,9.0,75.0,3.2,1.0,2.0,2.0,3.0,JTZ435,3360,none,A1,NaN,NaN,"[althold, tcas]"
30,a53b26,NaN,2.0,NaN,NaN,perhour,[],[],20,248.4,-18.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A1,NaN,NaN,NaN
80,a5d668,36000.0,2.0,10.0,3.0,perhour,[],[],9800,0.6,-17.0,37700.0,400.6,220.8,0.0,1013.6,36000.0,239.1,NaN,NaN,NaN,NaN,NaN,1.0,2.0,NaN,NaN,NaN,NaN,NaN,A3,NaN,NaN,NaN
31,a6152a,33000.0,2.0,NaN,NaN,perhour,[],[],1317,11.4,-18.8,34575.0,495.5,37.7,NaN,NaN,NaN,NaN,38.508058,-76.203186,8.0,186.0,67.4,NaN,1.0,NaN,NaN,NaN,NaN,NaN,A3,0.0,NaN,NaN
62,a64df2,NaN,2.0,NaN,NaN,perhour,[],[],1032,210.0,-14.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A2,NaN,NaN,NaN

In [ ]:
data['aircraft']